spring:
  application:
    name: greetingService

# bind GreetingConfiguration
greeting-service:
  greeting: "Olá"
  default-value: "Mundo"

# allow show all endpoints in Actuator, see /actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"